version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore ./MeetMe/MeetMe.sln
build:
  project: ./MeetMe/MeetMe.sln
  verbosity: minimal
notifications:
- provider: Email
  to:
  - vlado547@outlook.com
  on_build_failure: true
  on_build_status_changed: true
